name: tsviewer
channels:
  - defaults
dependencies:
  - anyio=3.5.0
  - appnope=0.1.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=21.4.0
  - babel=2.9.1
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bleach=4.1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.05.30
  - certifi=2023.5.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - comm=0.1.2
  - cryptography=39.0.1
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - icu=58.2
  - idna=3.3
  - intel-openmp=2021.4.0
  - ipykernel=6.19.2
  - ipython=8.12.0
  - ipython_genutils=0.2.0
  - jedi=0.18.1
  - jinja2=3.0.3
  - json5=0.9.6
  - jsonschema=4.17.3
  - jupyter_client=8.1.0
  - jupyter_core=5.3.0
  - jupyter_server=1.23.4
  - jupyterlab=3.5.3
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.10.3
  - libcxx=14.0.6
  - libffi=3.4.2
  - libiconv=1.16
  - libllvm11=11.1.0
  - libllvm14=14.0.6
  - libsodium=1.0.18
  - libuv=1.44.2
  - libxml2=2.10.3
  - libxslt=1.1.37
  - llvm-openmp=14.0.6
  - llvmlite=0.40.0
  - lxml=4.9.2
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - nbclassic=0.5.5
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nodejs=18.16.0
  - notebook=6.5.4
  - notebook-shim=0.2.2
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openssl=3.0.9
  - packaging=21.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.1.2
  - platformdirs=2.5.2
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=23.0.0
  - pyparsing=3.0.4
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.11.3
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.1
  - pytz=2022.7
  - pyzmq=25.1.0
  - readline=8.1.2
  - requests=2.29.0
  - send2trash=1.8.0
  - setuptools=67.8.0
  - six=1.16.0
  - sniffio=1.2.0
  - soupsieve=2.3.1
  - sqlite=3.41.2
  - stack_data=0.2.0
  - tbb=2021.8.0
  - terminado=0.17.1
  - testpath=0.6.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - tomli=2.0.1
  - tornado=6.2
  - traitlets=5.7.1
  - typing-extensions=4.1.1
  - typing_extensions=4.1.1
  - urllib3=1.26.16
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.37.1
  - xz=5.4.2
  - zeromq=4.3.4
  - zlib=1.2.13
  - pip:
    - astropy==5.3
    - blosc2==2.0.0
    - bokeh==2.4.3
    - cdasws==1.7.43
    - cdflib==0.4.9
    - cftime==1.6.2
    - colorama==0.4.6
    - contourpy==1.1.0
    - cycler==0.11.0
    - cython==0.29.35
    - dill==0.3.6
    - fonttools==4.40.0
    - geopack==1.0.10
    - gitdb==4.0.10
    - gitpython==3.1.31
    - hampel==0.0.5
    - hapiclient==0.2.5
    - isodate==0.6.1
    - joblib==1.2.0
    - jupyter-server-mathjax==0.2.6
    - jupyterlab-git==0.41.0
    - kiwisolver==1.4.4
    - matplotlib==3.7.1
    - msgpack==1.0.5
    - nbdime==3.2.1
    - netcdf4==1.6.4
    - numba==0.57.1
    - numexpr==2.8.4
    - pandas==2.0.2
    - parfor==2022.6.0
    - pillow==9.5.0
    - py-cpuinfo==9.0.0
    - pycwt==0.4.0b0
    - pyerfa==2.0.0.3
    - pyspedas==1.4.38
    - pytplot-mpl-temp==2.1.39
    - pywavelets==1.4.1
    - pyyaml==6.0
    - scipy==1.10.1
    - smmap==5.0.0
    - tables==3.8.0
    - tqdm==4.65.0
    - tzdata==2023.3
    - viresclient==0.11.1
    - xarray==2023.5.0
